const LANGUAGES = [
  // English (6)
  { code:'en-US', name:'English (US)',       flag:'🇺🇸' },
  { code:'en-GB', name:'English (UK)',       flag:'🇬🇧' },
  { code:'en-CA', name:'English (CA)',       flag:'🇨🇦' },
  { code:'en-AU', name:'English (AU)',       flag:'🇦🇺' },
  { code:'en-IN', name:'English (IN)',       flag:'🇮🇳' },
  { code:'en-ZA', name:'English (ZA)',       flag:'🇿🇦' },
  // Spanish (4)
  { code:'es-ES', name:'Español (ES)',       flag:'🇪🇸' },
  { code:'es-MX', name:'Español (MX)',       flag:'🇲🇽' },
  { code:'es-AR', name:'Español (AR)',       flag:'🇦🇷' },
  { code:'es-US', name:'Español (US)',       flag:'🇺🇸' },
  // Portuguese (2)
  { code:'pt-BR', name:'Português (BR)',     flag:'🇧🇷' },
  { code:'pt-PT', name:'Português (PT)',     flag:'🇵🇹' },
  // French (2)
  { code:'fr-FR', name:'Français (FR)',      flag:'🇫🇷' },
  { code:'fr-CA', name:'Français (CA)',      flag:'🇨🇦' },
  // German (3)
  { code:'de-DE', name:'Deutsch (DE)',       flag:'🇩🇪' },
  { code:'de-AT', name:'Deutsch (AT)',       flag:'🇦🇹' },
  { code:'de-CH', name:'Deutsch (CH)',       flag:'🇨🇭' },
  // Dutch (2)
  { code:'nl-NL', name:'Nederlands (NL)',    flag:'🇳🇱' },
  { code:'nl-BE', name:'Nederlands (BE)',    flag:'🇧🇪' },
  // Scandinavian (4)
  { code:'sv-SE', name:'Svenska (SE)',       flag:'🇸🇪' },
  { code:'da-DK', name:'Dansk (DK)',         flag:'🇩🇰' },
  { code:'nb-NO', name:'Norsk (NO)',         flag:'🇳🇴' },
  { code:'is-IS', name:'Íslenska (IS)',      flag:'🇮🇸' },
  // Italian
  { code:'it-IT', name:'Italiano (IT)',      flag:'🇮🇹' },
  // Slavic (10)
  { code:'ru-RU', name:'Русский (RU)',       flag:'🇷🇺' },
  { code:'pl-PL', name:'Polski (PL)',        flag:'🇵🇱' },
  { code:'cs-CZ', name:'Čeština (CZ)',       flag:'🇨🇿' },
  { code:'sk-SK', name:'Slovenčina (SK)',    flag:'🇸🇰' },
  { code:'uk-UA', name:'Українська (UA)',    flag:'🇺🇦' },
  { code:'hr-HR', name:'Hrvatski (HR)',      flag:'🇭🇷' },
  { code:'sr-RS', name:'Српски (RS)',        flag:'🇷🇸' },
  { code:'bg-BG', name:'Български (BG)',     flag:'🇧🇬' },
  { code:'sl-SI', name:'Slovenščina (SI)',   flag:'🇸🇮' },
  { code:'mk-MK', name:'Македонски (MK)',    flag:'🇲🇰' },
  // Other European (5)
  { code:'ro-RO', name:'Română (RO)',        flag:'🇷🇴' },
  { code:'ca-ES', name:'Català (ES)',        flag:'🇪🇸' },
  { code:'el-GR', name:'Ελληνικά (GR)',      flag:'🇬🇷' },
  { code:'fi-FI', name:'Suomi (FI)',         flag:'🇫🇮' },
  { code:'hu-HU', name:'Magyar (HU)',        flag:'🇭🇺' },
  // East Asian (4)
  { code:'ja-JP', name:'Japanese (JP)',      flag:'🇯🇵' },
  { code:'zh-CN', name:'Chinese (CN)',       flag:'🇨🇳' },
  { code:'zh-TW', name:'Chinese (TW)',       flag:'🇹🇼' },
  { code:'ko-KR', name:'Korean (KR)',        flag:'🇰🇷' },
  // Southeast Asian (10)
  { code:'th-TH', name:'Thai (TH)',          flag:'🇹🇭' },
  { code:'vi-VN', name:'Tiếng Việt (VN)',    flag:'🇻🇳' },
  { code:'id-ID', name:'Bahasa Indonesia',   flag:'🇮🇩' },
  { code:'ms-MY', name:'Bahasa Melayu (MY)', flag:'🇲🇾' },
  { code:'ms-BN', name:'Bahasa Melayu (BN)', flag:'🇧🇳' },
  { code:'tl-PH', name:'Filipino (PH)',      flag:'🇵🇭' },
  { code:'my-MM', name:'Myanmar (MM)',       flag:'🇲🇲' },
  { code:'km-KH', name:'Khmer (KH)',         flag:'🇰🇭' },
  { code:'lo-LA', name:'Lao (LA)',           flag:'🇱🇦' },
  { code:'mn-MN', name:'Монгол (MN)',        flag:'🇲🇳' },
  // South Asian (16)
  { code:'hi-IN', name:'Hindi (IN)',         flag:'🇮🇳' },
  { code:'bn-IN', name:'Bengali (IN)',       flag:'🇮🇳' },
  { code:'bn-BD', name:'Bengali (BD)',       flag:'🇧🇩' },
  { code:'ur-IN', name:'Urdu (IN)',          flag:'🇮🇳' },
  { code:'ur-PK', name:'Urdu (PK)',          flag:'🇵🇰' },
  { code:'pa-IN', name:'Punjabi (IN)',       flag:'🇮🇳' },
  { code:'gu-IN', name:'Gujarati (IN)',      flag:'🇮🇳' },
  { code:'mr-IN', name:'Marathi (IN)',       flag:'🇮🇳' },
  { code:'te-IN', name:'Telugu (IN)',        flag:'🇮🇳' },
  { code:'kn-IN', name:'Kannada (IN)',       flag:'🇮🇳' },
  { code:'ml-IN', name:'Malayalam (IN)',     flag:'🇮🇳' },
  { code:'ta-IN', name:'Tamil (IN)',         flag:'🇮🇳' },
  { code:'or-IN', name:'Odia (IN)',          flag:'🇮🇳' },
  { code:'si-LK', name:'Sinhala (LK)',       flag:'🇱🇰' },
  { code:'ne-NP', name:'Nepali (NP)',        flag:'🇳🇵' },
  { code:'dv-MV', name:'Dhivehi (MV)',       flag:'🇲🇻' },
  // Middle East & Africa (18)
  { code:'ar-SA', name:'Arabic (SA)',        flag:'🇸🇦' },
  { code:'ar-AE', name:'Arabic (AE)',        flag:'🇦🇪' },
  { code:'ar-EG', name:'Arabic (EG)',        flag:'🇪🇬' },
  { code:'tr-TR', name:'Türkçe (TR)',        flag:'🇹🇷' },
  { code:'he-IL', name:'עברית (IL)',         flag:'🇮🇱' },
  { code:'fa-IR', name:'فارسی (IR)',         flag:'🇮🇷' },
  { code:'sw-KE', name:'Kiswahili (KE)',     flag:'🇰🇪' },
  { code:'am-ET', name:'Amharic (ET)',       flag:'🇪🇹' },
  { code:'zu-ZA', name:'isiZulu (ZA)',       flag:'🇿🇦' },
  { code:'yo-NG', name:'Yoruba (NG)',        flag:'🇳🇬' },
  { code:'ig-NG', name:'Igbo (NG)',          flag:'🇳🇬' },
  { code:'ha-NG', name:'Hausa (NG)',         flag:'🇳🇬' },
  { code:'so-SO', name:'Soomaali (SO)',      flag:'🇸🇴' },
  { code:'rw-RW', name:'Kinyarwanda (RW)',   flag:'🇷🇼' },
  { code:'mg-MG', name:'Malagasy (MG)',      flag:'🇲🇬' },
  { code:'uz-UZ', name:'O\'zbek (UZ)',       flag:'🇺🇿' },
  { code:'kk-KZ', name:'Қазақша (KZ)',       flag:'🇰🇿' },
  { code:'ky-KG', name:'Кыргызча (KG)',      flag:'🇰🇬' },
  // Pacific & Other (6)
  { code:'haw-US', name:'Hawaiian (US)',     flag:'🇺🇸' },
  { code:'mi-NZ',  name:'Māori (NZ)',        flag:'🇳🇿' },
  { code:'sm-WS',  name:'Samoan (WS)',       flag:'🇼🇸' },
  { code:'to-TO',  name:'Tongan (TO)',       flag:'🇹🇴' },
  { code:'fj-FJ',  name:'Fijian (FJ)',       flag:'🇫🇯' },
  { code:'cy-GB',  name:'Cymraeg (GB)',      flag:'🇬🇧' },
];

module.exports = {
  LANGUAGES
};
