'use strict';

/**
 * fast-export.js
 * 
 * Implements a pure-FFmpeg pipeline for video cuts and silent region removal.
 * Optionally overlays static styles (padding layout, rounded corners, drop shadows)
 * by merging single-frame images generated by the frontend.
 */

const { app, shell } = require('electron');
const path = require('path');
const fs = require('fs');
const { spawn, spawnSync } = require('child_process');
const ffmpegManager = require('./ffmpeg-manager');

/**
 * Converts a base64 data URL to a temporary image file on disk.
 */
function saveBase64ToTempFile(dataUrl, prefix) {
  if (!dataUrl) return null;
  try {
    const matches = dataUrl.match(/^data:image\/([a-zA-Z+]+);base64,(.+)$/);
    if (!matches || matches.length !== 3) return null;
    const ext = matches[1];
    const data = matches[2];
    const buffer = Buffer.from(data, 'base64');
    const tempPath = path.join(
      app.getPath('temp'),
      `mictab_${prefix}_${Date.now()}_${Math.random().toString(36).substring(2, 7)}.${ext}`
    );
    fs.writeFileSync(tempPath, buffer);
    return tempPath;
  } catch (err) {
    console.error(`[Fast Export] Failed to save temporary image ${prefix}:`, err);
    return null;
  }
}

/**
 * Executes a fast export process using native FFmpeg filters and segments.
 */
async function runFastExport(opts, editorWindow, setProcessCb) {
  const {
    filePath, format, filename: rawFilename, segments, mutedSegments,
    viewport, includePadding, includeRadius, includeShadow,
    bgDataUrl, maskDataUrl, hwaccel, fps: fpsChoice,
    cw, ch, dw, dh
  } = opts;

  const dir = path.dirname(filePath);
  const filename = (rawFilename || 'export').replace(/\\/g, '/').split('/').pop().replace(/\.[^.]+$/, '');
  const outName = filename + '.' + format;
  const outPath = path.join(dir, outName);

  // Filter out active segments
  const activeSegs = (segments || []).filter(s => !s.isDeleted);
  if (!activeSegs.length) {
    return { ok: false, error: 'No active segments to export.' };
  }

  // Ensure FFmpeg is installed
  if (!ffmpegManager.isFFmpegInstalled()) {
    try {
      await ffmpegManager.downloadFFmpeg();
    } catch (e) {
      return { ok: false, error: 'FFmpeg is required for fast export. Setup failed: ' + e.message };
    }
  }
  const ffmpegPath = ffmpegManager.ffmpegBinPath();

  // Create temporary files for background layout and corner mask if provided
  let bgTempPath = null;
  let maskTempPath = null;

  if (includePadding && bgDataUrl) {
    bgTempPath = saveBase64ToTempFile(bgDataUrl, 'bg');
  }
  if (includeRadius && maskDataUrl) {
    maskTempPath = saveBase64ToTempFile(maskDataUrl, 'mask');
  }

  // Calculate even dimensions for canvas and foreground video
  const canvasW = Math.round(cw || 1920) % 2 === 0 ? Math.round(cw || 1920) : Math.round(cw || 1920) + 1;
  const canvasH = Math.round(ch || 1080) % 2 === 0 ? Math.round(ch || 1080) : Math.round(ch || 1080) + 1;
  const destW = Math.round(dw || 1920) % 2 === 0 ? Math.round(dw || 1920) : Math.round(dw || 1920) - 1;
  const destH = Math.round(dh || 1080) % 2 === 0 ? Math.round(dh || 1080) : Math.round(dh || 1080) - 1;

  // Determine muted regions
  const mutedRanges = (mutedSegments || []).map(s => ({ start: s.startSec, end: s.endSec }));

  // Probe source for audio stream
  let hasAudio = false;
  try {
    const infoOut = spawnSync(ffmpegPath, ['-i', filePath], { timeout: 10000 });
    const infoStr = infoOut.stderr ? infoOut.stderr.toString() : '';
    hasAudio = /Stream.*Audio/i.test(infoStr);
  } catch (e) {
    console.warn('[Fast Export] Audio probe failed, assuming no audio', e.message);
  }

  console.log(`[Fast Export] Running: format=${format}, audio=${hasAudio}, padding=${includePadding}, radius=${includeRadius}, shadow=${includeShadow}`);
  console.log(`[Fast Export] Layout size: ${canvasW}x${canvasH}, Video size: ${destW}x${destH}`);

  const totalOutDuration = activeSegs.reduce((sum, s) => sum + (s.endSec - s.startSec), 0);

  // Build FFmpeg Arguments list
  const args = [];
  const isMac = process.platform === 'darwin';
  const isWin = process.platform === 'win32';
  const hw = hwaccel || 'auto';

  // Enable HW Acceleration flags
  if (hw === 'gpu' || hw === 'auto') {
    if (isMac) {
      args.push('-hwaccel', 'videotoolbox');
    } else if (isWin && hw === 'gpu') {
      args.push('-hwaccel', 'd3d11va');
    }
  }

  // Inputs
  args.push('-i', filePath); // Input [0]

  let bgInputIdx = -1;
  let maskInputIdx = -1;
  let nextInputIdx = 1;

  if (bgTempPath) {
    args.push('-loop', '1', '-t', String(totalOutDuration), '-i', bgTempPath); // Input [1]
    bgInputIdx = nextInputIdx++;
  }
  if (maskTempPath) {
    args.push('-loop', '1', '-t', String(totalOutDuration), '-i', maskTempPath); // Input [2]
    maskInputIdx = nextInputIdx++;
  }

  // Construct filter_complex to trim and merge cuts/silences
  const videoFilters = [];
  const audioFilters = [];
  const concatInputs = [];

  activeSegs.forEach((seg, i) => {
    const start = seg.startSec;
    const end = seg.endSec;
    const isMuted = mutedRanges.some(m =>
      m.start <= start + 0.01 && m.end >= end - 0.01
    );

    // Trim video
    videoFilters.push(`[0:v]trim=start=${start}:end=${end},setpts=PTS-STARTPTS[v${i}]`);

    if (hasAudio) {
      if (isMuted) {
        audioFilters.push(`[0:a]atrim=start=${start}:end=${end},asetpts=PTS-STARTPTS,volume=0[a${i}]`);
      } else {
        audioFilters.push(`[0:a]atrim=start=${start}:end=${end},asetpts=PTS-STARTPTS[a${i}]`);
      }
      concatInputs.push(`[v${i}][a${i}]`);
    } else {
      concatInputs.push(`[v${i}]`);
    }
  });

  // Concat segments
  let filterComplex = '';
  let mapArgs = [];

  if (hasAudio) {
    const concatFilter = `${concatInputs.join('')}concat=n=${activeSegs.length}:v=1:a=1[concatv][outa]`;
    filterComplex = [...videoFilters, ...audioFilters, concatFilter].join(';');
    mapArgs = ['-map', '[outv]', '-map', '[outa]'];
  } else {
    const concatFilter = `${concatInputs.join('')}concat=n=${activeSegs.length}:v=1:a=0[concatv]`;
    filterComplex = [...videoFilters, concatFilter].join(';');
    mapArgs = ['-map', '[outv]'];
  }

  // Apply padding, radius, and shadows using the loaded static images or dynamic filters
  let lastStream = '[concatv]';
  let bgStream = null;

  if (includePadding) {
    if (viewport && viewport.bgMode === 'blur') {
      const blurSigma = (viewport && viewport.blurIntensity) || 30;
      // Split the concatenated video: one for background, one for foreground
      filterComplex += `;${lastStream}split=2[vbg][vfg]`;
      // Create the blurred background dynamically from [vbg]
      // Scale directly to target canvas size and blur/dim it using eq filter
      filterComplex += `;[vbg]scale=${canvasW}:${canvasH},gblur=sigma=${Math.max(1, Math.round(blurSigma * 0.8))},eq=contrast=0.5:brightness=-0.25[bgblurred]`;
      bgStream = '[bgblurred]';
      lastStream = '[vfg]';
    } else if (bgInputIdx !== -1) {
      // Static background image/color/gradient loaded from temp file
      bgStream = `[${bgInputIdx}:v]`;
    }
  }

  // 1. Scale video to destW x destH
  filterComplex += `;${lastStream}scale=${destW}:${destH}[scaledv]`;
  lastStream = '[scaledv]';

  // 2. Apply rounded corner mask if checked
  if (includeRadius && maskInputIdx !== -1) {
    filterComplex += `;${lastStream}[${maskInputIdx}:v]alphamerge[maskedv]`;
    lastStream = '[maskedv]';
  }

  // 3. Compose foreground video and optional drop shadow on background image
  if (bgStream) {
    if (includeShadow && viewport && viewport.shadow > 0) {
      const shadowSize = Math.max(2, Math.round(viewport.shadow));
      const shadowOffset = Math.round(viewport.shadow * 0.3);

      if (maskInputIdx !== -1) {
        filterComplex += `;color=c=black:s=${destW}x${destH}:d=${totalOutDuration}[blackbase];[blackbase][${maskInputIdx}:v]alphamerge[blackshape]`;
      } else {
        filterComplex += `;color=c=black:s=${destW}x${destH}:d=${totalOutDuration}[blackshape]`;
      }
      
      // Symmetrically pad the black shape with transparent black, then blur it to form the drop shadow
      filterComplex += `;[blackshape]pad=iw+${shadowSize * 2}:ih+${shadowSize * 2}:${shadowSize}:${shadowSize}:color=black@0[paddedshape]`;
      filterComplex += `;[paddedshape]boxblur=luma_radius=${shadowSize}:luma_power=1[shadowv]`;

      // Overlay shadow on background layout with offset, then overlay video on top
      filterComplex += `;${bgStream}[shadowv]overlay=(W-w)/2:(H-h)/2+${shadowOffset}[bgshadowed]`;
      filterComplex += `;[bgshadowed]${lastStream}overlay=(W-w)/2:(H-h)/2:shortest=1[outv]`;
    } else {
      // Simply overlay centered onto background layout
      filterComplex += `;${bgStream}${lastStream}overlay=(W-w)/2:(H-h)/2:shortest=1[outv]`;
    }
  } else {
    // No background layout padding selected: output the scaled/masked stream directly
    filterComplex += `;${lastStream}copy[outv]`;
  }

  // Build target encoding formats
  if (format === 'webm') {
    args.push('-c:v', 'libvpx-vp9', '-crf', '24', '-b:v', '0', '-row-mt', '1', '-threads', '8', '-speed', '6');
    if (hasAudio) args.push('-c:a', 'libopus');
  } else if (format === 'mp4') {
    args.push('-pix_fmt', 'yuv420p');
    if (hw === 'gpu' || (hw === 'auto' && isMac)) {
      if (isMac) {
        args.push('-c:v', 'h264_videotoolbox', '-q:v', '85');
      } else if (isWin) {
        args.push('-c:v', 'h264_nvenc', '-preset', 'p4', '-cq', '19');
      } else {
        args.push('-c:v', 'libx264', '-preset', 'fast', '-crf', '18');
      }
    } else {
      args.push('-c:v', 'libx264', '-preset', 'fast', '-crf', '18');
    }
    if (hasAudio) args.push('-c:a', 'aac', '-b:a', '192k');
  } else if (format === 'mov') {
    args.push('-pix_fmt', 'yuv420p');
    if (hw === 'gpu' || (hw === 'auto' && isMac)) {
      if (isMac) {
        args.push('-c:v', 'h264_videotoolbox', '-q:v', '85');
      } else {
        args.push('-c:v', 'libx264', '-preset', 'fast', '-crf', '18');
      }
    } else {
      args.push('-c:v', 'libx264', '-preset', 'fast', '-crf', '18');
    }
    if (hasAudio) args.push('-c:a', 'aac', '-b:a', '192k');
  } else if (format === 'gif') {
    // Strip audio map for GIF format
    mapArgs = ['-map', '[outv]'];
    args.push('-vf', 'fps=15,scale=640:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse');
  }

  // Parse FPS choice
  if (fpsChoice && fpsChoice !== 'source') {
    args.push('-r', String(fpsChoice));
  }

  // Add shortest to prevent trailing audio stream issues
  if (hasAudio && format !== 'gif') {
    args.push('-shortest');
  }

  args.push('-filter_complex', filterComplex, ...mapArgs, '-y', outPath);

  console.log('[Fast Export] Spawn FFmpeg:', ffmpegPath, args.join(' '));

  const sendProgress = (pct, eta) => {
    if (editorWindow && !editorWindow.isDestroyed()) {
      editorWindow.webContents.send('veditor-export-progress', { percent: pct, eta: eta || null });
    }
  };

  sendProgress(2);

  return new Promise((resolve) => {
    const proc = spawn(ffmpegPath, args, { stdio: ['ignore', 'pipe', 'pipe'] });
    if (setProcessCb) setProcessCb(proc);

    let stderrBuf = '';
    const startTime = Date.now();

    proc.stderr.on('data', (chunk) => {
      stderrBuf += chunk.toString();
      const timeMatch = stderrBuf.match(/time=\s*(\d+):(\d+):(\d+)\.(\d+)/g);
      if (timeMatch && totalOutDuration > 0) {
        const last = timeMatch[timeMatch.length - 1];
        const m = last.match(/time=\s*(\d+):(\d+):(\d+)\.(\d+)/);
        if (m) {
          const elapsed = (+m[1]) * 3600 + (+m[2]) * 60 + (+m[3]) + (+m[4]) / 100;
          const pct = Math.min(99, Math.round((elapsed / totalOutDuration) * 100));
          const wallElapsed = (Date.now() - startTime) / 1000;
          const eta = pct > 2 ? Math.round((wallElapsed / pct) * (100 - pct)) : null;
          sendProgress(Math.max(2, pct), eta);
        }
      }
      if (stderrBuf.length > 4096) stderrBuf = stderrBuf.slice(-2048);
    });

    proc.on('close', (code) => {
      // Cleanup temporary background and mask files
      if (bgTempPath && fs.existsSync(bgTempPath)) {
        try { fs.unlinkSync(bgTempPath); } catch (_) {}
      }
      if (maskTempPath && fs.existsSync(maskTempPath)) {
        try { fs.unlinkSync(maskTempPath); } catch (_) {}
      }

      if (code !== 0) {
        const errMsg = code === null ? 'Export cancelled' : `FFmpeg exited with code ${code}`;
        const stderrTail = stderrBuf.slice(-500).trim();
        console.error('[Fast Export] FFmpeg error:', errMsg, '\nstderr:', stderrTail);
        if (editorWindow && !editorWindow.isDestroyed()) {
          editorWindow.webContents.send('veditor-export-done', { ok: false, error: errMsg, cancelled: code === null });
        }
        try { if (fs.existsSync(outPath)) fs.unlinkSync(outPath); } catch (_e) {}
        resolve({ ok: false, error: errMsg, cancelled: code === null });
        return;
      }

      console.log('[Fast Export] Success:', outPath);
      sendProgress(100);
      shell.showItemInFolder(outPath);
      if (editorWindow && !editorWindow.isDestroyed()) {
        editorWindow.webContents.send('veditor-export-done', { ok: true, path: outPath });
      }
      resolve({ ok: true, path: outPath });
    });
  });
}

module.exports = {
  runFastExport
};
